-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.empresas
(
    emp_cod integer NOT NULL DEFAULT nextval('empresas_emp_cod_seq'::regclass),
    emp_nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT empresas_pkey PRIMARY KEY (emp_cod)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    usu_cod integer NOT NULL DEFAULT nextval('usuarios_usu_cod_seq'::regclass),
    usu_nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    usu_pwd character varying(50) COLLATE pg_catalog."default" NOT NULL,
    usu_rol integer NOT NULL DEFAULT 0,
    CONSTRAINT usuarios_pkey PRIMARY KEY (usu_cod, usu_nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios_telemetria
(
    ute_cod integer NOT NULL DEFAULT nextval('usuarios_aplicacion_usa_cod_seq'::regclass),
    ute_emp_cod integer NOT NULL,
    ute_nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    ute_pwd character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ute_centro_padre integer,
    ute_centro integer,
    ute_pdv integer,
    ute_jefe_area integer,
    ute_ruta integer,
    ute_empresa integer,
    CONSTRAINT usuarios_telemetria_pkey PRIMARY KEY (ute_emp_cod, ute_nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios_token
(
    ust_cod integer NOT NULL DEFAULT nextval('usuarios_token_ust_cod_seq'::regclass),
    ust_usuario integer NOT NULL DEFAULT 0,
    ust_usos integer NOT NULL DEFAULT 1,
    ust_token character varying(300) COLLATE pg_catalog."default",
    ust_activo boolean DEFAULT false,
    CONSTRAINT usuarios_token_pkey PRIMARY KEY (ust_cod, ust_usuario)
);

ALTER TABLE IF EXISTS public.usuarios_telemetria
    ADD CONSTRAINT fk_usuarios_telemetria_empresas FOREIGN KEY (ute_emp_cod)
    REFERENCES public.empresas (emp_cod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.usuarios_token
    ADD CONSTRAINT fk_usuarios_token_usuarios FOREIGN KEY (ust_usuario)
    REFERENCES public.usuarios (usu_cod) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;